### ISSUE TITLE
Setting orgUrl is not required

### ISSUE THREAD

**Issue by vringar** [amardeep2006/camunda-okta-oidc-sso#2]
If the org URL is not set, it will be computed with the issuer URL. See [here](https://github.com/okta/okta-spring-boot/blob/fbcc9ed92dcf3839c6a94609b1877828450ebbe3/sdk/src/main/java/com/okta/spring/boot/sdk/env/OktaSdkPropertiesEnvironmentPostProcessor.java#L57-L70)

**Comment by amardeep2006** [comment]
you are correct. Will fix in camunda 7.20 examples

**Comment by amardeep2006** [comment]
fixed
