### ISSUE TITLE
Getting error when going to localhost:8080

### ISSUE THREAD

**Issue by patozgg** [amardeep2006/camunda-okta-oidc-sso#3]
I am getting the following error when visiting localhost:8080.  Any clues on what it might be? 

java.lang.NullPointerException: Cannot invoke "org.camunda.bpm.webapp.impl.security.auth.UserAuthentication.getProcessEngineName()" because "authentication" is null

Thank you!

**Comment by amardeep2006** [comment]
@patozgg  Yes I am aware of this and had added it to readme of the repo as well. Camunda made some breaking changes in version 7.19 . This was working till camunda 7.18.
I am working on changes required and plan to release by this weekend.

**Comment by kbarnesMCC** [comment]
@amardeep2006 just chiming in to say I'm also curious to see if/how you may have addressed this authentication null issue.

**Comment by amardeep2006** [comment]
@patozgg @kbarnesMCC Thanks for your feedback and patience.
Finally got time today and fixed the issue. Please test and let me know.

I also upgraded it to Camunda 7.20 and Springboot 3.2

**Comment by amardeep2006** [comment]
> @amardeep2006 just chiming in to say I'm also curious to see if/how you may have addressed this authentication null issue.

I had to add a new class https://github.com/amardeep2006/camunda-okta-oidc-sso/blob/main/src/main/java/com/example/workflow/config/IdentityProviderPlugin.java

Here are few reference links

     https://docs.camunda.org/security/notices/#notice-85
     https://docs.camunda.org/manual/7.19/user-guide/security/#authentication-cache
     https://github.com/camunda-consulting/camunda-7-code-examples/tree/main/snippets/springboot-security-sso
     https://github.com/camunda/camunda-bpm-platform/issues/3475
     https://github.com/camunda/camunda-bpm-platform/issues/3689

**Comment by patozgg** [comment]
Thank you!

**Comment by amardeep2006** [comment]
closing the issue. Also upgraded example to camunda 7.21 and springboot 3.3.0
